import { Selector, Role} from 'testcafe';
import doVisualRegression from "../../Util/vrtUtil";
import signIn from "../../pages/signIn";
import { period,quarterToDate,quarter,halfYear,halfYearToDate,yearToDate,yearToGo,fullYear, addnl1, addnl2,addnl3, seriesDropdown, varianceAnalysis, scenario1, scenario2, scenario3 } from "../../pages/navigationPanel"
import { tree,SignIn,editOption,Login, table, switchToIframe, analyze,simulate, switchToMainWindow, wait5000, plan, model } from '../../pages/common';
import {navigationPanel0,navigationPanelFullYear, navigationPanelJanuary, navigationPanelYtD } from "../../pages/navigationPanel";
fixture `Conditional Formatting`

.meta('ID','VDT-3140')
    .meta({'author': 'Automation','Date':'31-Aug-2020'})
    .meta('SEVERITY','Critical')
    .meta('TEST_RUN','1.7.0')

// .before(async ctx  => {
//     ctx.someProp = 123;
//     console.log('Test started..',currentFixture);
// })
// .after(async ctx  => {
//     console.log(ctx.newProp); // > abc
//     console.log('Test Ended..',currentFixture);
// });

test
.page `https://app.powerbi.com/groups/ca77a2d0-e137-4422-93e6-fb581b1cb7a4/reports/e6c5f87a-3a6c-4fda-8beb-b1ecc99aa99b/ReportSection`

    .meta('ID','VDT-3140')
    .meta('SEVERITY','blocker')
    ('NodeLevel Conditional Format-Enabled Compare Series-1', async t => {
        await SignIn()  
        await t
        //.wait(40000)
        await switchToMainWindow()
        await t
        .wait(60000)
        .click(Selector('#editBtn'))
        .wait(5000)
        await switchToIframe()
        await t
        .click(Selector('#wizbar span').withText('Model'))
        .click(Selector('#sandbox-host span').withText('New'))
        .click(Selector('#sandbox-host div').withText('Load valQ model with sample data').nth(17))
        .click(Selector('#modal-root button').withText('Yes'))
        .click(Selector('#modal-root div').withText('Personal Finance').nth(11))
        await model()
        await t
        .click(Selector('#sandbox-host .expand-collapse.node-collapsed'))
        .doubleClick(Selector('#sandbox-host div').withText('N2: Salary Net Income').nth(22))
        .click(Selector('#modal-root span').withText('Conditional Formatting'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'SanNetIncome_CF')
        await t
        .click(Selector('#modal-root button').withText('Finish'))
        .click(Selector('#sandbox-host .expand-collapse.node-collapsed').nth(1))
        .doubleClick(Selector('#sandbox-host div').withText('N12A: Essentials').nth(22))
        .click(Selector('#modal-root span').withText('Conditional Formatting'))
        .click(Selector('#modal-root .form-icon').nth(1))
        .click(Selector('#modal-root .bf-ui-form-input.form-input').nth(1))
        .pressKey('backspace')
        .pressKey('backspace')
        .pressKey('backspace')
        .typeText(Selector('#modal-root .bf-ui-form-input.form-input').nth(1),'10')
        .click(Selector('#modal-root .bf-ui-form-input.form-input').nth(2))
        .pressKey('backspace')
        .pressKey('backspace')
        .pressKey('backspace')
        .typeText(Selector('#modal-root .bf-ui-form-input.form-input').nth(2),'20')
        .click(Selector('#modal-root .form-icon').nth(5))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'SanNetIncome_CF_Change')
        await t
        .click(Selector('#modal-root button').withText('Finish'))
        .click(Selector('#sandbox-host .expand-collapse.node-collapsed').nth(1))
        .doubleClick(Selector('#sandbox-host div').withText('N26: Groceries').nth(22))
        .click(Selector('#modal-root span').withText('Conditional Formatting'))
        .click(Selector('#modal-root .form-icon').nth(2))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Groceries_CF')
        await t
        .click(Selector('#modal-root button').withText('Finish'))
        .hover(Selector('#N26').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('5')
        .pressKey('0')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Groceries_Sim')
        await t
        .hover(Selector('#N26').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('#N26 .d2VDTReset').nth(1))
        .click(Selector('#N12A .d2VDTToggleOverlay'))
        .click(Selector('#N12 .d2VDTToggleOverlay'))
        .hover(Selector('#N2').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('1')
        .pressKey('0')
        .pressKey('backspace')
        .pressKey('backspace')
        .pressKey('(')
        .pressKey('1')
        .pressKey('0')
        .pressKey(')')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Essentials_Sim-Tree')
        await table()
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Essentials_Sim-Table')
        await tree()
        await t
        .hover(Selector('#N2').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('8')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'SalNetIncome_Sim-Tree')
        await table()
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'SalNetIncome_Sim-Table')
        await tree()
        await t
        .hover(Selector('#N2').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('2')
        .pressKey('0')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'SalNetIncome_Sim2-Tree')
        await table()
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'SalNetIncome_Sim2-Table')
        await tree()
        await t
        .hover(Selector('#N2').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('1')
        .pressKey('0')
        .pressKey('backspace')
        .pressKey('backspace')
        .pressKey('(')
        .pressKey('2')
        .pressKey('0')
        .pressKey(')')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'SalNetIncome_Sim3-Tree')
        await table()
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'SalNetIncome_Sim3-Table')
        await tree()
        await t
        .click(Selector('#N1 .d2VDTToggleOverlay'))
        .click(Selector('#N12 .d2VDTToggleOverlay'))
        .hover(Selector('#N12A').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('2')
        .pressKey('1')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim-Tree')
        await table()
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim-Table')
        await tree()
        await t
        .hover(Selector('#N12A').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('1')
        .pressKey('0')
        .pressKey('backspace')
        .pressKey('backspace')
        .pressKey('(')
        .pressKey('1')
        .pressKey('1')
        .pressKey(')')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Essentials_Sim2-Tree')
        await table()
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Essentials_Sim2-Table')
        await tree()
        await t
        .click(Selector('#N12A .d2VDTToggleOverlay'))
        .hover(Selector('#N30').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('1')
        .pressKey('0')
        .pressKey('backspace')
        .pressKey('backspace')
        .pressKey('(')
        .pressKey('1')
        .pressKey('2')
        .pressKey(')')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Essentials_Sim3-Tree')
        await table()
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Essentials_Sim3-Table')
        await tree()
        await t
        .hover(Selector('#N12A').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('2')
        .pressKey('5')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Essentials_Sim4-Tree')
        await table()
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Essentials_Sim4-Table')
     
    });



    test
    .page `https://app.powerbi.com/groups/ca77a2d0-e137-4422-93e6-fb581b1cb7a4/reports/e6c5f87a-3a6c-4fda-8beb-b1ecc99aa99b/ReportSection`

    .meta('ID','VDT-3140')
    .meta('SEVERITY','blocker')
    ('NodeLevel Conditional Format-Enabled Compare Series-2', async t => {
        await SignIn()  
        await t
        //.wait(40000)
        await switchToMainWindow()
        await t
        .wait(60000)
        .click(Selector('#editBtn'))
        .wait(25000)
        await switchToIframe()
        await t
        .click(Selector('#wizbar span').withText('Model'))
        .click(Selector('#sandbox-host span').withText('New'))
        .click(Selector('#sandbox-host div').withText('Load valQ model with sample data').nth(17))
        .click(Selector('#modal-root button').withText('Yes'))
        .click(Selector('#modal-root div').withText('Personal Finance').nth(11))
        await model()
        await t
        .doubleClick(Selector('#sandbox-host div').withText('N1: Income').nth(22))
        .click(Selector('#modal-root span').withText('Conditional Formatting'))
        .click(Selector('#modal-root span').withText('Custom rule: Overwrites default or any inherited r'))
        .click(Selector('#modal-root .bf-ui-form-input.form-input'))
        .pressKey('backspace')
        .pressKey('backspace')
        .pressKey('backspace')
        .typeText(Selector('#modal-root .bf-ui-form-input.form-input'),'17000')
        .click(Selector('#modal-root .bf-ui-form-input.form-input').nth(1))
        .pressKey('backspace')
        .pressKey('backspace')
        .pressKey('backspace')
        .typeText(Selector('#modal-root .bf-ui-form-input.form-input').nth(1),'18000')
        .click(Selector('#modal-root .bf-ui-form-input.form-input').nth(2))
        .pressKey('backspace')
        .pressKey('backspace')
        .pressKey('backspace')
        .typeText(Selector('#modal-root .bf-ui-form-input.form-input').nth(2),'21000')
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_CF')
        await t
        .click(Selector('#modal-root button').withText('Finish'))
        .hover(Selector('#N1').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('1')
        .pressKey('1')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim-Tree')
        await table()
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim-Table')
        await tree()
        await t
        .click(Selector('#N1').find('path.d2VDTNode.d2VDTFocus'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim-DetPg')
        await t
        .hover(Selector('#N1').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('5')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim2-Tree')
        await table()
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim2-Table')
        await tree()
        await t
        .click(Selector('#N1').find('path.d2VDTNode.d2VDTFocus'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim2-DetPg')
        await t
        .hover(Selector('#N1').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('1')
        .pressKey('0')
        .pressKey('backspace')
        .pressKey('backspace')
        .pressKey('(')
        .pressKey('1')
        .pressKey('0')
        .pressKey(')')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim3-Tree')
        await table()
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim3-Table')
        await tree()
        await t
        .click(Selector('#N1').find('path.d2VDTNode.d2VDTFocus'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim3-DetPg')
        await t
        .hover(Selector('#N1').find('path.d2VDTNode.d2VDTFocus'))
        .click(Selector('g').find('rect.d2VDTshowSim'))
        .click(Selector('g').find('text.d2VDTIcon'))
        .doubleClick(Selector('#sandbox-host .grid-cell').nth(17))
        .click(Selector('#sandbox-host .grid-cell').nth(17))
        .pressKey('1')
        .pressKey('0')
        .pressKey('backspace')
        .pressKey('backspace')
        .pressKey('(')
        .pressKey('2')
        .pressKey('0')
        .pressKey(')')
        .click(Selector('.d2VDTClose'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim4-Tree')
        await table()
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim4-Table')
        await tree()
        await t
        .click(Selector('#N1').find('path.d2VDTNode.d2VDTFocus'))
        await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Income_Sim4-DetPg')

    });