import { Selector, Role} from 'testcafe';
import doVisualRegression from "../../Util/vrtUtil";
import signIn from "../../pages/signIn";
import { VDT2680_Variance_Analysis, Variance_Analysis_UI_Control } from "../../pages/urlPage";
import { period,quarterToDate,VAScenarioSelection,sizeToFit,PctVariance,AbsVariance,VABaseline,VAComparison,VATimeAggregation,quarter,halfYear,halfYearToDate,yearToDate,yearToGo,fullYear, addnl1, addnl2,addnl3, seriesDropdown, varianceAnalysis, scenario1, scenario2, scenario3 } from "../../pages/varianceAnalysis"
import { tree, table, switchToIframe, analyze,simulate, switchToMainWindow, wait5000, plan } from '../../pages/common';
import xPathToCss from 'xpath-to-css';
const signInVarAnalysis = Role(Variance_Analysis_UI_Control, signIn, { preserveUrl: true })

fixture `VarianceAnalysis`
    .meta('ID','VDT-2925')
    .meta({'author': 'Automation','Date':'31-Aug-2020'})
    .meta('SEVERITY','Critical')
    .meta('TEST_RUN','1.7.0')

    //SET 1--> Baseline-Budget, Comparison-Additional 1,Additional 2,Additional 3
    //SET 2--> Baseline-Budget, Comparison-Additional 2,Additional 3,Forecast
    //SET-3--> Baseline-Budget, Comparison-Additional 3,Forecast,Allocation Series 1
    //SET-4--> Baseline-Budget, Comparison-Forecast,Allocation Series 1,Additional 1
    //SET-5--> Baseline-Budget, Comparison-Allocation Series 1,Additional 1,Additional 2

test
    .meta('ID','VDT-2925')
    .meta('SEVERITY','blocker')
    ('UI Control Validation-Absolute Variance-No Scenario', async t => {
    await t
    .useRole(signInVarAnalysis)
    .maximizeWindow()
    .wait(70000)
    await t
    .click(Selector('#editBtn span').withText('Edit'))
    await switchToIframe()
    await analyze()
    await varianceAnalysis()
    await VAComparison('Additional 1')
    await VAComparison('Forecast')
    await VAComparison('Additional 2')
    await VAComparison('Additional 3')
    await sizeToFit()
    //Absolute Variance
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_FullYr')


    //Set 2
    await VAComparison('Additional 1')
    await VAComparison('Forecast')
    await sizeToFit()
    //Absolute Variance
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_FullYr')
    


    //Set 3
    await VAComparison('Additional 2')
    await VAComparison('Allocation Series 1')
    await sizeToFit()
    //Absolute Variance
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_FullYr')
    


    //Set 4
    await VAComparison('Additional 3')
    await VAComparison('Additional 1')
    await sizeToFit()
    //Absolute Variance
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_FullYr')
    


    //Set 5
    await VAComparison('Forecast')
    await VAComparison('Additional 2')
    await sizeToFit()
    //Absolute Variance
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_FullYr')
 


    });




    test
    .meta('ID','VDT-2925')
    .meta('SEVERITY','blocker')
    ('UI Control Validation-Absolute Variance-With Scenario', async t => {
    await t
    .useRole(signInVarAnalysis)
    .maximizeWindow()
    .wait(70000)
    await t
    .click(Selector('#editBtn span').withText('Edit'))
    await switchToIframe()
    await analyze()
    await varianceAnalysis()
    //WITH SCENARIO
    await VAScenarioSelection('Scenario 1')
    //Set 1
    await VAComparison('Additional 1')
    await VAComparison('Forecast')
    await VAComparison('Additional 2')
    await VAComparison('Additional 3')
    await sizeToFit()
    //Absolute Variance
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_FullYr')


    //Set 2
    await VAComparison('Additional 1')
    await VAComparison('Forecast')
    await sizeToFit()
    //Absolute Variance
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_FullYr')
    

    //Set 3
    await VAComparison('Additional 2')
    await VAComparison('Allocation Series 1')
    await sizeToFit()
    //Absolute Variance
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_FullYr')

    //Set 4
    await VAComparison('Additional 3')
    await VAComparison('Additional 1')
    await sizeToFit()
    //Absolute Variance
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_FullYr')


    //Set 5
    await VAComparison('Forecast')
    await VAComparison('Additional 2')
    await sizeToFit()
    //Absolute Variance
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_FullYr')
    });



    test
    .meta('ID','VDT-2925')
    .meta('SEVERITY','blocker')
    ('UI Control Validation-Percentage Variance-No Scenario', async t => {
    await t
    .useRole(signInVarAnalysis)
    .maximizeWindow()
    .wait(70000)
    await t
    .click(Selector('#editBtn span').withText('Edit'))
    await switchToIframe()
    await analyze()
    await varianceAnalysis()
    await VAComparison('Additional 1')
    await VAComparison('Forecast')
    await VAComparison('Additional 2')
    await VAComparison('Additional 3')
    await sizeToFit()
    
    //Percentage Variance
    await PctVariance()
    await AbsVariance()
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_FullYr')


    //Set 2
    
    //Percentage Variance
    await VAComparison('Forecast')
    await VAComparison('Additional 1')
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_FullYr')


    //Set 3
    
    //Percentage Variance
    await VAComparison('Additional 2')
    await VAComparison('Allocation Series 1')
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_FullYr')


    //Set 4
   
    //Percentage Variance
    await VAComparison('Additional 3')
    await VAComparison('Additional 1')
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_FullYr')


    //Set 5
    //Percentage Variance
    await VAComparison('Forecast')
    await VAComparison('Additional 2')
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_FullYr')

    });



    test
    .meta('ID','VDT-2925')
    .meta('SEVERITY','blocker')
    ('UI Control Validation-Percentage Variance-With Scenario', async t => {
    await t
    .useRole(signInVarAnalysis)
    .maximizeWindow()
    .wait(70000)
    await t
    .click(Selector('#editBtn span').withText('Edit'))
    await switchToIframe()
    await analyze()
    await varianceAnalysis()
    await VAComparison('Additional 1')
    await VAComparison('Forecast')
    await VAComparison('Additional 2')
    await VAComparison('Additional 3')
    await sizeToFit()
    
    //Percentage Variance
    await PctVariance()
    await AbsVariance()
    await VAScenarioSelection('Scenario 1')

    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-1_FullYr')


    //Percentage Variance
    await VAComparison('Forecast')
    await VAComparison('Additional 1')
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-2_FullYr')


    //Percentage Variance
    await VAComparison('Additional 2')
    await VAComparison('Allocation Series 1')
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-3_FullYr')


    //Percentage Variance
    await VAComparison('Additional 3')
    await VAComparison('Additional 1')
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-4_FullYr')


    //Percentage Variance
    await VAComparison('Forecast')
    await VAComparison('Additional 2')
    await VATimeAggregation('Periodic')
    await VATimeAggregation('Full Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_Periodic')
    await VATimeAggregation('Quarter-to-date')
    await VATimeAggregation('Periodic')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_QTD')
    await VATimeAggregation('Quarter')
    await VATimeAggregation('Quarter-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_Quarter')
    await VATimeAggregation('Half Year')
    await VATimeAggregation('Quarter')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_HalfYr')
    await VATimeAggregation('Half Year-to-date')
    await VATimeAggregation('Half Year')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_HalfYrTD')
    await VATimeAggregation('Year-to-date')
    await VATimeAggregation('Half Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_YTD')
    await VATimeAggregation('Year-to-go')
    await VATimeAggregation('Year-to-date')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_YTGo')
    await VATimeAggregation('Full Year')
    await VATimeAggregation('Year-to-go')
    await doVisualRegression(t.testRun.test.testFile.currentFixture.name, t.testRun.test.name, 'Set-5_FullYr')



    });